version: '3.8'

services:

  backend:
    build: ./server
    ports:
      - 5001:5001
    environment:
      # postgresql://your_postgres_user:your_postgres_password@db:5432/your_postgres_db
      - DATABASE_URL=your_postgres_connection_uri
      - SECRET_KEY=your_secret_key
    volumes:
      - ./server/:/usr/server/
    command: python3 -m uvicorn app:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - db

  frontend:
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  default: 
    name: hello_fastapi
