version: '3.8'

services:

  backend:
    build: ./server
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./server/:/usr/server/
    command: python3 -m uvicorn app:app --reload --host 0.0.0.0 --port 5001
    depends_on:
      - db

  frontend:
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  default: 
    name: hello_fastapi